name: Build hugo webpages
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tech-squawks repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}
      - name: Install Hugo CLI
        run: brew install hugo
      - name: Build Hugo Website 
        run: (cd web; hugo)
