name: tech-squawks-valaidate
on: [pull_request]
jobs:
  check-code-pulumi-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Hugo CLI
        run: brew install hugo
      - name: Render Static Website
        run: (cd web; hugo)
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Hugo CLI
        run: brew install hugo
      - name: Render Static Website
        run: (cd web; hugo)
  pulumi-prod-preview:
    runs-on: ubuntu-latest
    needs: build-website
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install 'embedme' tool
        run: npm i embedme
      - name: Embed code examples
        run: npx embedme  --source-root code  web/content/**/*.md --silent
      - name: Install Hugo CLI
        run: brew install hugo
      - name: Render Static Website
        run: (cd web; hugo)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Project Dependencies
        run: npm i
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: production
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  
