name: Build hugo webpages
on: [push]
jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Hugo CLI
        run: brew install hugo
      - name: Render Static Website
        run: (cd web; hugo)
