name: Build hugo webpages
on: [push]
jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Hugo CLI
        run: brew install hugo
      - name: Render Static Website
        run: (cd web; hugo)
  pulumi-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Pulumi CLI
        run: curl -fsSL https://get.pulumi.com | sh
      - name: Execute Preview
        run: pulumi preview
  
