name: Validate that webpage can be built.
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '14'
      - run: (cd web; hugo)
