baseURL = "http://www.techsquawks.com/"
languageCode = "en-us"
title = "Tech Squawks"
themesdir = "themes"
theme = "hugo-theme-relearn"

[params]
alwaysopen = false
editUrl = 'https://github.com/MichaelStott/tech-squawks/tree/main/web/content/'
showVisitedLinks = false
collapsibleMenu = true
disableBreadcrumb = false
disableInlineCopyToClipBoard = true
disableNextPrev = false
disableLandingPageButton = false
titleSeparator = "::"
themeVariant = ["light", "dark"]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Tech Squawks Repository"
identifier = "repo"
url = "https://github.com/MichaelStott/tech-squawks"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bug'></i> Report an Issue"
identifier = "issues"
url = "https://github.com/MichaelStott/tech-squawks/issues/new/choose"
weight = 20

[outputs]
home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]
