baseURL = "http://www.techsquawks.com/"
languageCode = "en-us"
title = "Tech Squawks"
themesdir = "themes"
theme = "hugo-theme-relearn"

[params]
  alwaysopen = false
  showVisitedLinks = true
  collapsibleMenu = true
  disableBreadcrumb = false
  disableInlineCopyToClipBoard = true
  disableNextPrev = false
  disableLandingPageButton = false
  titleSeparator = "::"
  themeVariant = [ "light", "dark" ]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Tech Squawks Repository"
identifier = "repo"
url = "https://github.com/MichaelStott/tech-squawks"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bug'></i> Report an Issue"
identifier = "issues"
url = "https://github.com/MichaelStott/tech-squawks/issues/new"
weight = 20

[outputs]
  home = ["HTML", "RSS", "SEARCH"]