baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tech Squawks"
theme = "hugo-theme-relearn"

[params]
alwaysopen = false
disableSearch = true
collapsibleMenu = true
themeVariant = [ "light", "dark" ]

